spring:
       datasource:

        # datasource1 (web):
              url: jdbc:postgresql://${RAILWAY_TCP_PROXY_DOMAIN}:${RAILWAY_TCP_PROXY_PORT}/${PGDATABASE}
              username: ${PGUSER}
              password: ${POSTGRES_PASSWORD}
              driver-class-name: org.postgresql.Driver

        #datasource2 (local):
             #  url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
             #  username: ${PGUSER}
             #  password: ${PGPASSWORD}


       jpa:
        open-in-view: false
        hibernate:
         ddl-auto: update


