spring:
       datasource:

          #datasource1 (web):

              url: jdbc:postgresql://${RAILWAY_TCP_PROXY_DOMAIN}:${RAILWAY_TCP_PROXY_PORT}/${PGDATABASE}
              username: ${PGUSER}
              password: ${POSTGRES_PASSWORD}
              driver-class-name: org.postgresql.Driver

          #datasource2 (local):

              url1: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
              username1: ${PGUSER}
              password1: ${PGPASSWORD}
              port: ${PORT}
              driver-class-name1: org.postgresql.Driver


       jpa:
        open-in-view: false
        hibernate:
         ddl-auto: create


